### ISSUE TITLE
FetchError

### ISSUE THREAD

**Issue by wendyliga** [C4illin/ASFclaim#51]
encounter issue when running on `ASF 5.5.0.11 - linux-x64 - b924e3b`

full log
```
Only runs on the last 40 games
error running '[object Object]':
FetchError: request to http://10.0.12.43:1242/Api/Command failed, reason: socket hang up
    at ClientRequest.<anonymous> (file:///usr/src/app/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:526:35)
    at Socket.socketOnEnd (node:_http_client:519:9)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}
```

**Comment by KaneHart** [comment]
Have this exact issue. Anyone figure a way to resolve this? I used docker and just ran it and first thing that came up.

**Comment by C4illin** [comment]
It sounds like an IPC error with ASF. Did it work before?

**Comment by KaneHart** [comment]
This was my first time ever trying it. All I did was run the docker-compose and boom that was what I got. Not sure if there is more I'm suppose to do? I assume after that web interface would be accessible?

**Comment by wendyliga** [comment]
this issue occurs because asfclaim is booted up before asf. solve this issue on docker by using `depends_on`

**Comment by KaneHart** [comment]
There an example of where you add depends_on?

**Comment by wendyliga** [comment]
```
services:
  asf:
     ....
  asfclaim:
    image: ghcr.io/c4illin/asfclaim:master
    container_name: asfclaim
    restart: unless-stopped
    depends_on: asf
    environment:
      - ASF_PORT=1242
      - ASF_HOST=localhost
      - ASF_PASSWORD=hunter2
```
